export const CHANGE_CURRENT_SONG = "CHANGE_CURRENT_SONG";
export const CHANGE_PLAY_LIST = "CHANGE_PLAY_LIST";
export const CHANGE_CURRENT_SONG_INDEX = "CHANGE_CURRENT_SONG_INDEX";
export const CHANGE_SEQUENCE = 'CHANGE_SEQUENCE';
export const CHANGE_LYRICS = 'CHANGE_LYRICS';
export const CHANGE_CURRENT_LYRIC_INDEX = 'CHANGE_CURRENT_LYRIC_INDEX';
export const CHANGE_SHOW_PLAYLIST = 'CHANGE_SHOW_PLAYLIST';